### ISSUE TITLE
Integration with Vetur - getting hints in the parent component

### ISSUE THREAD

**Issue by bissolli** [andrewvasilchuk/vue-typed-emit#4]
Hey @andrewvasilchuk is there a way to get the type hints in the other way of the chain?
I mean, when I listen to the event in the parent component my payload is always `any`! Did you manage to get it working?

Where the event is actually implemented it works perfectly!

I've mentioned you here btw
https://github.com/vuejs/vetur/pull/2558#issuecomment-753612714

**Comment by andrewvasilchuk** [comment]
@bissolli Do you still need it? Vue have made a large progress with IDE hints in [Volar](https://github.com/johnsoncodehk/volar). Also you won't need `vue-typed-emit` library in Vue 3 since it provides [an ability to provide types of emits](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits).

**Comment by bissolli** [comment]
> @bissolli Do you still need it? Vue have made a large progress with IDE hints in [Volar](https://github.com/johnsoncodehk/volar). Also you won't need `vue-typed-emit` library in Vue 3 since it provides [an ability to provide types of emits](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits).

You are right Andrew, not needed anymore!

Thanks =)
